<?php  //[STAMP] 9fd9a2f661d2db205160caf9c5d41a52
namespace tests\codeception\backend\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
