<?php
return [
    'index'=>[
        'class'=>'backend\controllers\BatchAttentionActions\IndexAction'
    ],
    'create'=>[
        'class'=>'backend\controllers\BatchAttentionActions\CreateAction'
    ],
    'update'=>[
        'class'=>'backend\controllers\BatchAttentionActions\UpdateAction'
    ],
    'delete'=>[
        'class'=>'backend\controllers\BatchAttentionActions\DeleteAction'
    ],
    'setauthlist'=>[
        'class'=>'backend\controllers\BatchAttentionActions\SetAuthListAction'
    ],
    'getauthlist'=>[
        'class'=>'backend\controllers\BatchAttentionActions\GetAuthListAction'
    ]
];