<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 15-12-14
 * Time: 上午12:06
 */
return
[
    //进入房间和退出房间 live.mblive.cn
    'qiniu_create_living'=>'ZhiBoQiNiuCreateLiving',
    'qiniu_enter_room'=>'ZhiBoQiNiuEnterRoom',
    'qiniu_robot_enter_room'=>'ZhiBoQiNiuRobotEnterRoom',
    'qiniu_update_living'=>'ZhiBoQiNiuUpdateLiving',
    'create_living'=>'ZhiBoCreateLiving',
    'update_living'=>'ZhiBoUpdateLiving',
    'finish_living'=>'ZhiBoFinishLiving',
    'enter_room'=>'ZhiBoEnterRoom',
    'quit_room'=>'ZhiBoQuitRoom',
    'group_manager'=>'ZhiBoGroupManager',
    'send_danmaku'=>'ZhiBoDanmaku',
    'living_finish_info'=>'ZhiBoGetFinishLivingInfo',
    'qiniu_living_params'=>'ZhiBoGetQiNiuLivingParams',
    'qiniu_living_params_more'=>'ZhiBoGetMoreQiNiuLivingParams',
    'get_robot'=>'ZhiBoGetRobot',
    'get_share_info'=>'ZhiBoGetShareInfo',
    'check_living_private'=>'ZhiBoCheckLivingPrivate',
    'get_living_views_share'=>'ZhiBoGetViewsShare',
    //送礼物 gift.mblive.cn
    'get_contribution_board'=>'ZhiBoGetContributionBoard',
    'get_goods'=>'ZhiBoGetGoods',
    'click_like'=>'ZhiBoClickLike',
    'get_gifts'=>'ZhiBoGetGifts',
    'send_gift'=>'ZhiBoSendGift',
    'grab_red_packets'=>'ZhiBoGrabRedPackets',
    'red_packets_list'=>'ZhiBoRedPacketsList',
    'generate_red_packets'=>'ZhiBoGenerateRedPackets',
    //充值、微信  微信端的各个功能  recharge.mblive.cn
    'ticket_to_cash'=>'ZhiBoTicketToCash',
    'get_other_pay_params'=>'ZhiBoGetOtherPayParams',
    'cancel_other_pay'=>'ZhiBoCancelOtherPay',
    'cancel_golds_pay'=>'ZhiBoCancelGoldsPay',
    'history_ticket_to_cash'=>'ZhiBoHistoryTicketToCash',
    'get_to_bean_goods'=>'ZhiBoGetToBeanGoods',
    'bind_weixin_for_cash'=>'ZhiBoBindWeixinForCash',
    'bind_alipay_for_cash'=>'ZhiBoBindAlipayForCash',
    'ticket_to_bean'=>'ZhiBoTicketToBean',
    'apple_pay_over'=>'ZhiBoApplePayOver',
    'ios_buy_verify'=>'ZhiBoIosBuyVerify',
    //剩余   front.mblive.cn
        'login'=>'ZhiBoLogin',
        'qiniu_login'=>'ZhiBoLoginQiNiu',
        'logout'=>'ZhiBoLogout',
        'update_key'=>'ZhiBoUpdateKey',
        'get_blacks'=>'ZhiBoGetBlacks',
        'set_black'=>'ZhiBoSetBlack',
        'cancel_black'=>'ZhiBoCancelBlack',
        'no_words'=>'ZhiBoNoWords',
        'heart_beat'=>'ZhiBoHeartBeat',
        'get_funs'=>'ZhiBoGetFuns',
        'get_manager_list'=>'ZhiBoGetManagerList',
        'get_attentions'=>'ZhiBoGetAttentions',
        'update_content'=>'ZhiBoUpdateContent',
        'user_search'=>'ZhiBoSearchUser',
        'attention'=>'ZhiBoAttention',
        'get_msg_accepters'=>'ZhiBoGetMsgAccepters',
        'manage_push_msg'=>'ZhiBoManagePushMsg',
        'cancel_attention'=>'ZhiBoCancelAttention',
        'get_validate_code'=>'ZhiBoGetValidateCode',
        'update_client'=>'ZhiBoUpdateClient',
        'get_client_info'=>'ZhiBoGetClientInfo',
        'get_multi_client_info'=>'ZhiBoGetMultiClientInfo',
        'complete_client'=>'ZhiBoCompleteClient',
        'get_hot_living'=>'ZhiBoGetHotLiving',
        'get_push_living_info'=>'ZhiBoGetPushLivingInfo',
        'get_attention_living'=>'ZhiBoGetAttentionLiving',
        'get_hot_living_master'=>'ZhiBoGetHotLivingMaster',
        'get_newest_living'=>'ZhiBoGetNewestLiving',
        'living_share'=>'ZhiBoLivingShare',
        'get_living_audience'=>'ZhiBoGetLivingAudience',
        'get_sum_ticket'=>'ZhiBoGetSumTicket',
        'get_carousels'=>'ZhiBoGetCarousels',
        'get_payments'=>'ZhiBoGetPayments',
        'get_system_params'=>'ZhiBoGetSystemParams',
        'get_unlogin_system_params'=>'ZhiBoGetNoLoginSystemParams',
        'add_report'=>'ZhiBoAddReport',
        'version_check'=>'ZhiBoVersionCheck',
        'ban_client'=>'ZhiBoBanClient',
        'get_peakdata'=>'ZhiBoGetPeakData',
        'create_fans_group'=>'ZhiBoCreateFansGroup',
        'fans_group_apply'=>'ZhiBoFansGroupApply',
        'fans_apply_approve'=>'ZhiBoFansApplyApprove',
        'get_fans_group_info'=>'ZhiBoGetFansGroupInfo',
        'update_fans_group_info'=>'ZhiBoUpdateFansGroupInfo',
        'group_member_list'=>'ZhiBoGroupMemberList',
        'group_member_privilege'=>'ZhiBoGroupMemberPrivilege',

        'kicking_fans'=>'ZhiBoKickingFans',
        'fans_group_dismiss'=>'ZhiBoFansGroupDismiss',
        'fans_apply_list'=>'ZhiBoFansApplyList',
        'fans_group_list'=>'ZhiBoFansGroupList',
        'add_dynamic'=>'ZhiBoAddDynamic',
        'add_comment'=>'ZhiBoAddComment',
        'get_comment_list'=>'ZhiBoGetCommentList',
        //'get_dynamic_list_android'=>'ZhiBoGetDynamicListAndroid',
        'get_dynamic_list'=>'ZhiBoGetDynamicList',
        'get_new_dynamic_list'=>'ZhiBoGetNewDynamicList',
        'cancel_dynamic'=>'ZhiBoCancelDynamic',
        'red_dynamic_reward'=>'ZhiBoRedDynamicReward',
        'dynamic_click_like'=>'ZhiBoDynamicClickLick',
        'get_dynamic_info'=>'ZhiBoGetDynamicInfo',
        'get_appshare_info' => 'ZhiBoGetAppShareInfo',
        'game_change_status'=>'niuniu\ZhiBoGameChangeStatus',
        'game_grab_seats'=>'niuniu\ZhiBoGameGrabSeats',
        'game_grab_banker'=>'niuniu\ZhiBoGameGrabBanker',
        'game_leave_seat'=>'niuniu\ZhiBoGameLeaveSeat',
        'game_periphery_bet'=>'niuniu\ZhiBoGameGrabPeriphery',
        'get_golds_goods_list'   =>'ZhiBoGetGoldsGoodsList',
        'add_golds_for_user_login'=>'ZhiBoDonateGoldsForUserLogin',
        'get_other_golds_pay_params' =>'ZhiBoGetGoldsPayParams',
        'create_living_approve' => 'ZhiBoCreateLivingApprove',
        'start_niuniu_game'=>'niuniu\ZhiBoStartNiuNiuGame',
        'get_game_info'=>'niuniu\ZhiBoGetGameInfo',
        'game_player_multiple'=>'niuniu\ZhiBoGamePlayerMultiple',
        'game_time_sync'=>'niuniu\ZhiBoGameTimeSync',
        'game_player_bet'=>'niuniu\ZhiBoGamePlayerBet',
        'ios_buy_golds_verify' =>'ZhiBoIosBuyGoldsVerify',
        'stop_living'=>'ZhiBoStopLiving',
        'app_startup_home_page_ad'=>'ZhiBoAppStartupHomePageAd',
        'click_like_sub_flowers'=>'ZhiBoClickLikeSubFlowers',
        'gather_error'=>'ZhiBoGatherError',
        'get_create_living_params'=>'ZhiBoGetCreateLivingParams',
        'qiniu_living_continue'=>'ZhiBoLivingContinue',
        'get_guess'=>'ZhiBoGetGuess',
        'fans_group_search'=>'ZhiBoFansGroupSearch',
        'living_room_search'=>'ZhiBoLivingRoomSearch',
        'get_startup_advertising' => 'ZhiBoGetStartUpAdvertising',
        'get_contacts_attentions' => 'ZhiBoGetContactsAttentions',
        'get_contacts_fansgroups' => 'ZhiBoGetContactsFansGroups',
        'get_admin_warning'=>'ZhiBoGetAdminWarning',
        'set_admin_warning'=>'ZhiBoSetAdminWarning',
        'delete_admin_warning'=>'ZhiBoDeleteAdminWarning',
        'living_face_approve'=>'ZhiBoFaceTotalStatistic',
    'get_token'=>'ZhiBoGetToken',
    'get_living_rtmp_url'=>'ZhiBoGetLivingRtmpUrl'
];