<?php
return [
    'index'=>[
        'class'=>'backend\controllers\PublicListActions\IndexAction',
    ],
    'create'=>[
        'class'=>'backend\controllers\PublicListActions\CreateAction',
    ],
    'attention'=>[
        'class'=>'backend\controllers\PublicListActions\AttentionReplyAction',
    ],
    'status'=>[
        'class'=>'backend\controllers\PublicListActions\StatusCacheAction',
    ],
    'createmsg'=>[
        'class'=>'backend\controllers\PublicListActions\CreateMsgAction',
    ],
    'delete'=>[
        'class'=>'backend\controllers\PublicListActions\DeleteEventAction'
    ],
    'update'=>[
        'class'=>'backend\controllers\PublicListActions\UpdateAction',
    ],
    'set_count'=>[
        'class'=>'backend\controllers\PublicListActions\SetCountAction',
    ]
];