
<?php
return [
    'index'=>[
        'class'=>'backend\controllers\CustomActions\IndexAction',
    ],
    'indexson'=>[
        'class'=>'backend\controllers\CustomActions\IndexSonAction',
    ],
    'download'=>[
        'class'=>'backend\controllers\CustomActions\DownloadAction',
    ],
    'islist'=>[
        'class'=>'backend\controllers\CustomActions\IsListAction',
    ],
    'delete'=>[
        'class'=>'backend\controllers\CustomActions\DeleteAction',
    ],
    'save'=>[
        'class'=>'backend\controllers\CustomActions\SaveAction',
    ],
    'create'=>[
        'class'=>'backend\controllers\CustomActions\CreateAction',
    ],
    'check'=>[
        'class'=>'backend\controllers\CustomActions\CheckMenuNumAction',
    ],
    'createson'=>[
        'class'=>'backend\controllers\CustomActions\CreateSonAction',
    ],
    'deleteson'=>[
        'class'=>'backend\controllers\CustomActions\DeleteSonAction',
    ],
    'update'=>[
        'class'=>'backend\controllers\CustomActions\UpdateAction',
    ],
    'updateson'=>[
        'class'=>'backend\controllers\CustomActions\UpdateSonAction',
    ]
];